version: "3.0"

services:
#   keycloack:
#     image: jboss/keycloack:6.0.1
#     environment:
#        KEYCLOACK_PASSWORD: admin123
#        keycloack_user: admin
#      ports:
#      - "8080:8080"
#      - "8181:8181"
#      comman:
#      - "-b"
#      - "0.0.0.0"
#      networks:
#        - employee_network

   db:
      image: mysql:8.0.17
      restart: always
      environment:
        MYSQL_DATABASE: db_employee
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root_pw
      ports:
        - 3306:3306
      networks:
        - employee_network

   backend:
        image: local/em-backend
        build: ./employee
        environment:
          - timezone=Europe/Berlin
          - spring_datasource_url=jdbc:mysql://db:3306/db_employee
        depends_on:
          - db
        restart: on-failure
        ports:
          - 8080:8080
        networks:
          - employee_network

   frontend:
      image: local/em-frontend
      build: ./employee-app
      environment:
        - timezone=Europe/Berlin
        - VUE_APP_API_URL='http://localhost:4200/'
      ports:
        - 4200:80
      networks:
        - employee_network

networks:
  employee_network:
